// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgA-N2SAnoqHVQpa2msRjuUsoci146M6Y',
    appId: '1:1049215248083:web:e48776bb0e2e44d38d1626',
    messagingSenderId: '1049215248083',
    projectId: 'applylog-application-tracker',
    authDomain: 'applylog-application-tracker.firebaseapp.com',
    storageBucket: 'applylog-application-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14fFwVsvsUJYrYBDSkhyWaMTdcR2qp7w',
    appId: '1:1049215248083:android:467ede87d61edb118d1626',
    messagingSenderId: '1049215248083',
    projectId: 'applylog-application-tracker',
    storageBucket: 'applylog-application-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlkVxjHQT0TyFYE4HDmQTN8kMs_g3UHg',
    appId: '1:1049215248083:ios:ac1659c386f591748d1626',
    messagingSenderId: '1049215248083',
    projectId: 'applylog-application-tracker',
    storageBucket: 'applylog-application-tracker.firebasestorage.app',
    iosBundleId: 'com.noshtechstudios.applylog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlkVxjHQT0TyFYE4HDmQTN8kMs_g3UHg',
    appId: '1:1049215248083:ios:ac1659c386f591748d1626',
    messagingSenderId: '1049215248083',
    projectId: 'applylog-application-tracker',
    storageBucket: 'applylog-application-tracker.firebasestorage.app',
    iosBundleId: 'com.noshtechstudios.applylog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgA-N2SAnoqHVQpa2msRjuUsoci146M6Y',
    appId: '1:1049215248083:web:607ed018896c59638d1626',
    messagingSenderId: '1049215248083',
    projectId: 'applylog-application-tracker',
    authDomain: 'applylog-application-tracker.firebaseapp.com',
    storageBucket: 'applylog-application-tracker.firebasestorage.app',
  );
}
